modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = "${description}"
logoFile = "${icon}"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "minelights.mixins.json"
