org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=false
org.gradle.configuration-cache=false
org.gradle.java.home=C:/Program Files/Microsoft/jdk-21.0.10.7-hotspot
org.gradle.java.installations.paths=C:/Program Files/Microsoft/jdk-17.0.18.8-hotspot,C:/Program Files/Microsoft/jdk-21.0.10.7-hotspot,C:/Program Files/Microsoft/jdk-25.0.1.8-hotspot

mod.name=MineLights
mod.id=minelights
mod.version=2.3.8
mod.description=MineLights is a Minecraft NeoForge mod that brings RGB lighting integrations to Minecraft Java Edition.
mod.authors=MegaBytesMe
mod.license=CC BY-NC-SA 4.0
mod.homepage=https://modrinth.com/mod/minelights
mod.sources=https://github.com/megabytesme/MineLights
mod.issues=https://github.com/megabytesme/MineLights/issues
mod.icon=assets/minelights/icon.png
mod.environment=client
mod.modrinth=https://modrinth.com/mod/minelights
mod.kofi=https://ko-fi.com/megabytesme
mod.discord=https://discord.gg/xw29pzbhtp
mod.group=megabytesme.minelights

publish.modrinth=5cN5qhbm
